// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { endpoints, streamEndpoints, type EndpointOperation, type EndpointPathParam, type EventByStreamOperation, type RequestByOperation, type RequestByStreamOperation, type ResponseByOperation, type StreamEndpointOperation } from "./endpoints.js";
import type { ContractCallOptions, ContractTransport, ContractTransportRequest, HttpMethod } from "./transport.js";

type ClientRequestShape = object;

type ClientOperation<Operation extends EndpointOperation> = (
  request: RequestByOperation[Operation],
  options?: ContractCallOptions,
) => Promise<ResponseByOperation[Operation]>;

type ClientStreamOperation<Operation extends StreamEndpointOperation> = (
  request: RequestByStreamOperation[Operation],
  options?: ContractCallOptions,
) => AsyncIterable<EventByStreamOperation[Operation]>;

export type ContractsClient = {
  project: {
    create: ClientOperation<"createProject">;
    get: ClientOperation<"getProject">;
    list: ClientOperation<"listProjects">;
    update: ClientOperation<"updateProject">;
    delete: ClientOperation<"deleteProject">;
  };
  projectWorkContext: {
    open: ClientOperation<"openProjectWorkContext">;
    renew: ClientOperation<"renewProjectWorkContext">;
  };
  task: {
    create: ClientOperation<"createTask">;
    get: ClientOperation<"getTask">;
    list: ClientOperation<"listTasks">;
    update: ClientOperation<"updateTask">;
    delete: ClientOperation<"deleteTask">;
  };
  session: {
    create: ClientOperation<"createSession">;
    get: ClientOperation<"getSession">;
    list: ClientOperation<"listSessions">;
    update: ClientOperation<"updateSession">;
    delete: ClientOperation<"deleteSession">;
    subscribe: ClientStreamOperation<"subscribeSessionEvents">;
  };
  skill: {
    create: ClientOperation<"createSkill">;
    get: ClientOperation<"getSkill">;
    list: ClientOperation<"listSkills">;
    update: ClientOperation<"updateSkill">;
    delete: ClientOperation<"deleteSkill">;
  };
  agent: {
    create: ClientOperation<"createAgent">;
    get: ClientOperation<"getAgent">;
    list: ClientOperation<"listAgents">;
    update: ClientOperation<"updateAgent">;
    delete: ClientOperation<"deleteAgent">;
  };
};

export function createContractsClient(transport: ContractTransport): ContractsClient {
  return {
    project: {
      create: (request, options) => executeOperation("createProject", request, transport, options),
      get: (request, options) => executeOperation("getProject", request, transport, options),
      list: (request, options) => executeOperation("listProjects", request, transport, options),
      update: (request, options) => executeOperation("updateProject", request, transport, options),
      delete: (request, options) => executeOperation("deleteProject", request, transport, options),
    },
    projectWorkContext: {
      open: (request, options) => executeOperation("openProjectWorkContext", request, transport, options),
      renew: (request, options) => executeOperation("renewProjectWorkContext", request, transport, options),
    },
    task: {
      create: (request, options) => executeOperation("createTask", request, transport, options),
      get: (request, options) => executeOperation("getTask", request, transport, options),
      list: (request, options) => executeOperation("listTasks", request, transport, options),
      update: (request, options) => executeOperation("updateTask", request, transport, options),
      delete: (request, options) => executeOperation("deleteTask", request, transport, options),
    },
    session: {
      create: (request, options) => executeOperation("createSession", request, transport, options),
      get: (request, options) => executeOperation("getSession", request, transport, options),
      list: (request, options) => executeOperation("listSessions", request, transport, options),
      update: (request, options) => executeOperation("updateSession", request, transport, options),
      delete: (request, options) => executeOperation("deleteSession", request, transport, options),
      subscribe: (request, options) => executeStreamOperation("subscribeSessionEvents", request, transport, options),
    },
    skill: {
      create: (request, options) => executeOperation("createSkill", request, transport, options),
      get: (request, options) => executeOperation("getSkill", request, transport, options),
      list: (request, options) => executeOperation("listSkills", request, transport, options),
      update: (request, options) => executeOperation("updateSkill", request, transport, options),
      delete: (request, options) => executeOperation("deleteSkill", request, transport, options),
    },
    agent: {
      create: (request, options) => executeOperation("createAgent", request, transport, options),
      get: (request, options) => executeOperation("getAgent", request, transport, options),
      list: (request, options) => executeOperation("listAgents", request, transport, options),
      update: (request, options) => executeOperation("updateAgent", request, transport, options),
      delete: (request, options) => executeOperation("deleteAgent", request, transport, options),
    },
  };
}

async function executeOperation<Operation extends EndpointOperation>(
  operation: Operation,
  request: RequestByOperation[Operation],
  transport: ContractTransport,
  options: ContractCallOptions | undefined,
): Promise<ResponseByOperation[Operation]> {
  const endpoint = endpoints[operation];
  const transportRequest = buildTransportRequest(endpoint, request, false);

  return transport.send<ResponseByOperation[Operation]>(transportRequest, options);
}

function executeStreamOperation<Operation extends StreamEndpointOperation>(
  operation: Operation,
  request: RequestByStreamOperation[Operation],
  transport: ContractTransport,
  options: ContractCallOptions | undefined,
): AsyncIterable<EventByStreamOperation[Operation]> {
  const endpoint = streamEndpoints[operation];
  const transportRequest = buildTransportRequest(endpoint, request, true);

  return transport.stream<EventByStreamOperation[Operation]>(transportRequest, options);
}

type TransportRequestEndpoint = {
  operationName: string;
  method: HttpMethod;
  pathTemplate: string;
  pathParams: readonly EndpointPathParam[];
  hasJsonBody: boolean;
};

function buildTransportRequest(
  endpoint: TransportRequestEndpoint,
  request: ClientRequestShape,
  acceptsEventStream: boolean,
): ContractTransportRequest {
  return {
    operationName: endpoint.operationName,
    method: endpoint.method,
    path: buildPath(endpoint.pathTemplate, endpoint.pathParams, request),
    body: buildJsonBody(endpoint.pathParams, endpoint.hasJsonBody, request),
    headers: buildHeaders(endpoint.hasJsonBody, acceptsEventStream),
  };
}

function buildPath(
  pathTemplate: string,
  pathParams: readonly EndpointPathParam[],
  request: ClientRequestShape,
): string {
  const requestRecord = request as Record<string, unknown>;
  let path = pathTemplate;

  for (const pathParam of pathParams) {
    const value = requestRecord[pathParam.wireName];

    if (value === undefined || value === null) {
      throw new Error(`missing path parameter ${pathParam.wireName}`);
    }

    path = path.replace(`{${pathParam.wireName}}`, encodeURIComponent(String(value)));
  }

  return path;
}

function buildJsonBody(
  pathParams: readonly EndpointPathParam[],
  hasJsonBody: boolean,
  request: ClientRequestShape,
): Record<string, unknown> | undefined {
  if (!hasJsonBody) {
    return undefined;
  }

  const requestRecord = request as Record<string, unknown>;
  const pathParamNames = new Set(pathParams.map((pathParam) => pathParam.wireName));

  return Object.fromEntries(
    Object.entries(requestRecord).filter(([fieldName]) => !pathParamNames.has(fieldName)),
  );
}

function buildHeaders(
  hasJsonBody: boolean,
  acceptsEventStream: boolean,
): Record<string, string> {
  const headers: Record<string, string> = {};

  if (hasJsonBody) {
    headers["content-type"] = "application/json";
  }

  if (acceptsEventStream) {
    headers["accept"] = "text/event-stream";
  }

  return headers;
}
