// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.
import { ContractTransportError, type ContractCallOptions, type ContractErrorPayload, type ContractTransport, type ContractTransportRequest } from "./transport.js";

export type FetchTransportOptions = {
  baseUrl?: string;
  fetch?: typeof globalThis.fetch;
};

export function createFetchTransport(
  options: FetchTransportOptions = {},
): ContractTransport {
  const fetchImplementation = options.fetch ?? globalThis.fetch;

  if (fetchImplementation === undefined) {
    throw new Error("global fetch is not available");
  }

  const baseUrl = options.baseUrl ?? "";

  async function execute(
    request: ContractTransportRequest,
    callOptions: ContractCallOptions | undefined,
  ): Promise<Response> {
    return fetchImplementation(resolveUrl(baseUrl, request.path), {
      method: request.method,
      headers: request.headers,
      body: request.body === undefined ? undefined : JSON.stringify(request.body),
      signal: callOptions?.signal,
    });
  }

  return {
    async send<TResponse>(request: ContractTransportRequest, callOptions?: ContractCallOptions): Promise<TResponse> {
      const response = await execute(request, callOptions);
      const responseBody = await readResponseBody(response);

      if (!response.ok) {
        throw toTransportError(response.status, responseBody);
      }

      return responseBody as TResponse;
    },

    async *stream<TEvent>(request: ContractTransportRequest, callOptions?: ContractCallOptions): AsyncGenerator<TEvent> {
      const response = await execute(request, callOptions);

      if (!response.ok) {
        throw toTransportError(response.status, await readResponseBody(response));
      }

      if (response.body === null) {
        throw new ContractTransportError({
          code: "stream_unavailable",
          message: `operation ${request.operationName} returned no response stream`,
          status: response.status,
          responseBody: null,
        });
      }

      yield* readEventStream<TEvent>(response.body, request);
    },
  };
}

export function resolveUrl(baseUrl: string, path: string): string {
  if (baseUrl === "") {
    return path;
  }

  return new URL(path, baseUrl).toString();
}

export function decodeErrorEnvelope(body: unknown): ContractErrorPayload | null {
  if (!isRecord(body)) {
    return null;
  }

  const error = body.error;

  if (!isRecord(error) || typeof error.code !== "string" || typeof error.message !== "string") {
    return null;
  }

  return {
    code: error.code,
    message: error.message,
  };
}

/** Yields one decoded event per server-sent frame until the response stream ends. */
async function* readEventStream<TEvent>(
  body: ReadableStream<Uint8Array>,
  request: ContractTransportRequest,
): AsyncGenerator<TEvent> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  try {
    for (;;) {
      const { done, value } = await reader.read();

      if (done) {
        return;
      }

      buffer += decoder.decode(value, { stream: true });

      for (;;) {
        const frame = takeEventFrame(buffer);

        if (frame === null) {
          break;
        }

        buffer = frame.rest;
        const event = decodeEventFrame<TEvent>(frame.frame, request);

        if (event !== null) {
          yield event;
        }
      }
    }
  } finally {
    await reader.cancel();
  }
}

/** Splits off the first complete frame, leaving any partial trailing frame buffered. */
function takeEventFrame(buffer: string): { frame: string; rest: string } | null {
  const separator = /\r?\n\r?\n/.exec(buffer);

  if (separator === null) {
    return null;
  }

  return {
    frame: buffer.slice(0, separator.index),
    rest: buffer.slice(separator.index + separator[0].length),
  };
}

/** Decodes one frame's `data` lines, returning null for comment-only keep-alive frames. */
function decodeEventFrame<TEvent>(
  frame: string,
  request: ContractTransportRequest,
): TEvent | null {
  const dataLines: string[] = [];

  for (const line of frame.split(/\r?\n/)) {
    if (line.startsWith(":")) {
      continue;
    }

    const separatorIndex = line.indexOf(":");

    if (separatorIndex === -1 || line.slice(0, separatorIndex) !== "data") {
      continue;
    }

    const value = line.slice(separatorIndex + 1);
    dataLines.push(value.startsWith(" ") ? value.slice(1) : value);
  }

  if (dataLines.length === 0) {
    return null;
  }

  const payload = dataLines.join("\n");

  let decoded: unknown;

  try {
    decoded = JSON.parse(payload) as unknown;
  } catch {
    throw new ContractTransportError({
      code: "stream_decode_error",
      message: `operation ${request.operationName} sent an event that is not valid JSON`,
      status: null,
      responseBody: payload,
    });
  }

  const errorPayload = decodeErrorEnvelope(decoded);

  if (errorPayload !== null) {
    throw new ContractTransportError({
      code: errorPayload.code,
      message: errorPayload.message,
      status: null,
      responseBody: decoded,
    });
  }

  return decoded as TEvent;
}

async function readResponseBody(response: Response): Promise<unknown> {
  const bodyText = await response.text();

  if (bodyText === "") {
    return null;
  }

  try {
    return JSON.parse(bodyText) as unknown;
  } catch {
    return bodyText;
  }
}

function toTransportError(status: number, responseBody: unknown): ContractTransportError {
  const decodedError = decodeErrorEnvelope(responseBody);

  if (decodedError !== null) {
    return new ContractTransportError({
      code: decodedError.code,
      message: decodedError.message,
      status,
      responseBody,
    });
  }

  return new ContractTransportError({
    code: "http_error",
    message: `HTTP request failed with status ${status}`,
    status,
    responseBody,
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}
