use ora_contracts::{
    FrontendEndpoint, FrontendPathParam, FrontendStreamEndpoint, export_typescript_bindings_to,
    frontend_endpoints, frontend_stream_endpoints,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

const GENERATED_FILE_HEADER: &str = "// This file was generated by `cargo xtask export-contracts`. Do not edit this file manually.\n";

/// Exports TypeScript DTOs and generated frontend SDK files into `packages/contracts/src`.
pub fn run_export_contracts(workspace_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let contracts_source_directory = workspace_root.join("packages/contracts/src");

    export_typescript_bindings_to(&contracts_source_directory)?;
    write_contract_runtime_files(
        &contracts_source_directory,
        frontend_endpoints(),
        frontend_stream_endpoints(),
    )?;
    remove_stale_generated_file(&contracts_source_directory.join("worktree.ts"))?;

    Ok(())
}

/// Writes the generated SDK runtime files that sit alongside the DTO exports.
fn write_contract_runtime_files(
    contracts_source_directory: &Path,
    endpoints: &[FrontendEndpoint],
    stream_endpoints: &[FrontendStreamEndpoint],
) -> Result<(), Box<dyn std::error::Error>> {
    write_generated_file(
        &contracts_source_directory.join("endpoints.ts"),
        &render_endpoints_module(endpoints, stream_endpoints),
    )?;
    write_generated_file(
        &contracts_source_directory.join("transport.ts"),
        &render_transport_module(),
    )?;
    write_generated_file(
        &contracts_source_directory.join("client.ts"),
        &render_client_module(endpoints, stream_endpoints),
    )?;
    write_generated_file(
        &contracts_source_directory.join("fetch.ts"),
        &render_fetch_module(),
    )?;
    write_generated_file(
        &contracts_source_directory.join("index.ts"),
        &render_index_module(),
    )?;

    Ok(())
}

/// Writes one generated file to disk, creating its parent directory when needed.
fn write_generated_file(
    output_path: &Path,
    contents: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent_directory) = output_path.parent() {
        fs::create_dir_all(parent_directory)?;
    }

    fs::write(output_path, contents)?;

    Ok(())
}

/// Removes one obsolete generated file when a contract family is no longer exported.
fn remove_stale_generated_file(output_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    if output_path.exists() {
        fs::remove_file(output_path)?;
    }

    Ok(())
}

/// Renders the endpoint manifest and operation type maps consumed by the generated client.
fn render_endpoints_module(
    endpoints: &[FrontendEndpoint],
    stream_endpoints: &[FrontendStreamEndpoint],
) -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);
    let imports = collect_contract_type_imports(endpoints, stream_endpoints);

    for (module_name, types) in imports {
        source.push_str("import type { ");
        source.push_str(&join_types(&types));
        source.push_str(" } from \"./");
        source.push_str(module_name);
        source.push_str(".js\";\n");
    }

    source.push_str("import type { HttpMethod } from \"./transport.js\";\n\n");
    source.push_str("export type EndpointPathParam = {\n");
    source.push_str("  rustFieldName: string;\n");
    source.push_str("  wireName: string;\n");
    source.push_str("};\n\n");
    source.push_str("export type FrontendEndpointDefinition = {\n");
    source.push_str("  operationName: string;\n");
    source.push_str("  method: HttpMethod;\n");
    source.push_str("  pathTemplate: string;\n");
    source.push_str("  requestType: string;\n");
    source.push_str("  responseType: string;\n");
    source.push_str("  pathParams: readonly EndpointPathParam[];\n");
    source.push_str("  hasJsonBody: boolean;\n");
    source.push_str("};\n\n");
    source.push_str("export type RequestByOperation = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": ");
        source.push_str(endpoint.request_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type ResponseByOperation = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": ");
        source.push_str(endpoint.response_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type EndpointOperation = keyof RequestByOperation;\n\n");
    source.push_str("export const endpoints = {\n");

    for endpoint in endpoints {
        source.push_str("  ");
        source.push_str(endpoint.operation_name);
        source.push_str(": {\n");
        source.push_str("    operationName: \"");
        source.push_str(endpoint.operation_name);
        source.push_str("\",\n");
        source.push_str("    method: \"");
        source.push_str(render_http_method(endpoint));
        source.push_str("\",\n");
        source.push_str("    pathTemplate: \"");
        source.push_str(endpoint.path_template);
        source.push_str("\",\n");
        source.push_str("    requestType: \"");
        source.push_str(endpoint.request_type);
        source.push_str("\",\n");
        source.push_str("    responseType: \"");
        source.push_str(endpoint.response_type);
        source.push_str("\",\n");
        source.push_str("    pathParams: ");
        source.push_str(&render_path_params(endpoint.path_params));
        source.push_str(",\n");
        source.push_str("    hasJsonBody: ");
        source.push_str(if endpoint.has_json_body {
            "true"
        } else {
            "false"
        });
        source.push_str(",\n");
        source.push_str("  },\n");
    }

    source.push_str("} satisfies Record<EndpointOperation, FrontendEndpointDefinition>;\n\n");
    source.push_str("export type StreamEndpointDefinition = {\n");
    source.push_str("  operationName: string;\n");
    source.push_str("  method: HttpMethod;\n");
    source.push_str("  pathTemplate: string;\n");
    source.push_str("  requestType: string;\n");
    source.push_str("  eventType: string;\n");
    source.push_str("  pathParams: readonly EndpointPathParam[];\n");
    source.push_str("  hasJsonBody: boolean;\n");
    source.push_str("};\n\n");
    source.push_str("export type RequestByStreamOperation = {\n");

    for stream_endpoint in stream_endpoints {
        source.push_str("  ");
        source.push_str(stream_endpoint.operation_name);
        source.push_str(": ");
        source.push_str(stream_endpoint.request_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type EventByStreamOperation = {\n");

    for stream_endpoint in stream_endpoints {
        source.push_str("  ");
        source.push_str(stream_endpoint.operation_name);
        source.push_str(": ");
        source.push_str(stream_endpoint.event_type);
        source.push_str(";\n");
    }

    source.push_str("};\n\n");
    source.push_str("export type StreamEndpointOperation = keyof RequestByStreamOperation;\n\n");
    source.push_str("export const streamEndpoints = {\n");

    for stream_endpoint in stream_endpoints {
        source.push_str("  ");
        source.push_str(stream_endpoint.operation_name);
        source.push_str(": {\n");
        source.push_str("    operationName: \"");
        source.push_str(stream_endpoint.operation_name);
        source.push_str("\",\n");
        source.push_str("    method: \"");
        source.push_str(render_stream_http_method(stream_endpoint));
        source.push_str("\",\n");
        source.push_str("    pathTemplate: \"");
        source.push_str(stream_endpoint.path_template);
        source.push_str("\",\n");
        source.push_str("    requestType: \"");
        source.push_str(stream_endpoint.request_type);
        source.push_str("\",\n");
        source.push_str("    eventType: \"");
        source.push_str(stream_endpoint.event_type);
        source.push_str("\",\n");
        source.push_str("    pathParams: ");
        source.push_str(&render_path_params(stream_endpoint.path_params));
        source.push_str(",\n");
        source.push_str("    hasJsonBody: ");
        source.push_str(if stream_endpoint.has_json_body {
            "true"
        } else {
            "false"
        });
        source.push_str(",\n");
        source.push_str("  },\n");
    }

    source.push_str("} satisfies Record<StreamEndpointOperation, StreamEndpointDefinition>;\n");

    source
}

/// Renders the transport interfaces and error types shared by generated clients.
fn render_transport_module() -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);

    source.push_str("export type HttpMethod = \"GET\" | \"POST\" | \"PUT\" | \"DELETE\";\n\n");
    source.push_str("export type ContractTransportRequest = {\n");
    source.push_str("  operationName: string;\n");
    source.push_str("  method: HttpMethod;\n");
    source.push_str("  path: string;\n");
    source.push_str("  body: unknown | undefined;\n");
    source.push_str("  headers: Record<string, string>;\n");
    source.push_str("};\n\n");
    source.push_str("export type ContractCallOptions = {\n");
    source.push_str("  signal?: AbortSignal;\n");
    source.push_str("};\n\n");
    source.push_str("export interface ContractTransport {\n");
    source.push_str(
        "  send<TResponse>(request: ContractTransportRequest, options?: ContractCallOptions): Promise<TResponse>;\n",
    );
    source.push_str(
        "  stream<TEvent>(request: ContractTransportRequest, options?: ContractCallOptions): AsyncIterable<TEvent>;\n",
    );
    source.push_str("}\n\n");
    source.push_str("export type ContractErrorPayload = {\n");
    source.push_str("  code: string;\n");
    source.push_str("  message: string;\n");
    source.push_str("};\n\n");
    source.push_str("export type ContractErrorEnvelope = {\n");
    source.push_str("  error: ContractErrorPayload;\n");
    source.push_str("};\n\n");
    source.push_str("export class ContractTransportError extends Error {\n");
    source.push_str("  readonly code: string;\n");
    source.push_str("  readonly status: number | null;\n");
    source.push_str("  readonly responseBody: unknown;\n\n");
    source.push_str("  constructor({\n");
    source.push_str("    code,\n");
    source.push_str("    message,\n");
    source.push_str("    status,\n");
    source.push_str("    responseBody,\n");
    source.push_str("  }: {\n");
    source.push_str("    code: string;\n");
    source.push_str("    message: string;\n");
    source.push_str("    status: number | null;\n");
    source.push_str("    responseBody: unknown;\n");
    source.push_str("  }) {\n");
    source.push_str("    super(message);\n");
    source.push_str("    this.name = \"ContractTransportError\";\n");
    source.push_str("    this.code = code;\n");
    source.push_str("    this.status = status;\n");
    source.push_str("    this.responseBody = responseBody;\n");
    source.push_str("  }\n");
    source.push_str("}\n");

    source
}

/// Renders the runtime-agnostic typed client that delegates HTTP execution to a transport.
fn render_client_module(
    endpoints: &[FrontendEndpoint],
    stream_endpoints: &[FrontendStreamEndpoint],
) -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);

    source.push_str(
        "import { endpoints, streamEndpoints, type EndpointOperation, type EndpointPathParam, type EventByStreamOperation, type RequestByOperation, type RequestByStreamOperation, type ResponseByOperation, type StreamEndpointOperation } from \"./endpoints.js\";\n",
    );
    source.push_str(
        "import type { ContractCallOptions, ContractTransport, ContractTransportRequest, HttpMethod } from \"./transport.js\";\n\n",
    );
    source.push_str("type ClientRequestShape = object;\n\n");
    source.push_str("type ClientOperation<Operation extends EndpointOperation> = (\n");
    source.push_str("  request: RequestByOperation[Operation],\n");
    source.push_str("  options?: ContractCallOptions,\n");
    source.push_str(") => Promise<ResponseByOperation[Operation]>;\n\n");
    source.push_str("type ClientStreamOperation<Operation extends StreamEndpointOperation> = (\n");
    source.push_str("  request: RequestByStreamOperation[Operation],\n");
    source.push_str("  options?: ContractCallOptions,\n");
    source.push_str(") => AsyncIterable<EventByStreamOperation[Operation]>;\n\n");
    source.push_str("export type ContractsClient = {\n");

    for (namespace, members) in group_client_members(endpoints, stream_endpoints) {
        source.push_str("  ");
        source.push_str(namespace);
        source.push_str(": {\n");

        for member in members {
            source.push_str("    ");
            source.push_str(member.member_name());
            source.push_str(match member {
                ClientMember::Unary(_) => ": ClientOperation<\"",
                ClientMember::Stream(_) => ": ClientStreamOperation<\"",
            });
            source.push_str(member.operation_name());
            source.push_str("\">;\n");
        }

        source.push_str("  };\n");
    }

    source.push_str("};\n\n");
    source.push_str(
        "export function createContractsClient(transport: ContractTransport): ContractsClient {\n",
    );
    source.push_str("  return {\n");

    for (namespace, members) in group_client_members(endpoints, stream_endpoints) {
        source.push_str("    ");
        source.push_str(namespace);
        source.push_str(": {\n");

        for member in members {
            source.push_str("      ");
            source.push_str(member.member_name());
            source.push_str(match member {
                ClientMember::Unary(_) => ": (request, options) => executeOperation(\"",
                ClientMember::Stream(_) => ": (request, options) => executeStreamOperation(\"",
            });
            source.push_str(member.operation_name());
            source.push_str("\", request, transport, options),\n");
        }

        source.push_str("    },\n");
    }

    source.push_str("  };\n");
    source.push_str("}\n\n");
    source.push_str("async function executeOperation<Operation extends EndpointOperation>(\n");
    source.push_str("  operation: Operation,\n");
    source.push_str("  request: RequestByOperation[Operation],\n");
    source.push_str("  transport: ContractTransport,\n");
    source.push_str("  options: ContractCallOptions | undefined,\n");
    source.push_str("): Promise<ResponseByOperation[Operation]> {\n");
    source.push_str("  const endpoint = endpoints[operation];\n");
    source.push_str(
        "  const transportRequest = buildTransportRequest(endpoint, request, false);\n\n",
    );
    source.push_str(
        "  return transport.send<ResponseByOperation[Operation]>(transportRequest, options);\n",
    );
    source.push_str("}\n\n");
    source
        .push_str("function executeStreamOperation<Operation extends StreamEndpointOperation>(\n");
    source.push_str("  operation: Operation,\n");
    source.push_str("  request: RequestByStreamOperation[Operation],\n");
    source.push_str("  transport: ContractTransport,\n");
    source.push_str("  options: ContractCallOptions | undefined,\n");
    source.push_str("): AsyncIterable<EventByStreamOperation[Operation]> {\n");
    source.push_str("  const endpoint = streamEndpoints[operation];\n");
    source
        .push_str("  const transportRequest = buildTransportRequest(endpoint, request, true);\n\n");
    source.push_str(
        "  return transport.stream<EventByStreamOperation[Operation]>(transportRequest, options);\n",
    );
    source.push_str("}\n\n");
    source.push_str("type TransportRequestEndpoint = {\n");
    source.push_str("  operationName: string;\n");
    source.push_str("  method: HttpMethod;\n");
    source.push_str("  pathTemplate: string;\n");
    source.push_str("  pathParams: readonly EndpointPathParam[];\n");
    source.push_str("  hasJsonBody: boolean;\n");
    source.push_str("};\n\n");
    source.push_str("function buildTransportRequest(\n");
    source.push_str("  endpoint: TransportRequestEndpoint,\n");
    source.push_str("  request: ClientRequestShape,\n");
    source.push_str("  acceptsEventStream: boolean,\n");
    source.push_str("): ContractTransportRequest {\n");
    source.push_str("  return {\n");
    source.push_str("    operationName: endpoint.operationName,\n");
    source.push_str("    method: endpoint.method,\n");
    source.push_str("    path: buildPath(endpoint.pathTemplate, endpoint.pathParams, request),\n");
    source
        .push_str("    body: buildJsonBody(endpoint.pathParams, endpoint.hasJsonBody, request),\n");
    source.push_str("    headers: buildHeaders(endpoint.hasJsonBody, acceptsEventStream),\n");
    source.push_str("  };\n");
    source.push_str("}\n\n");
    source.push_str("function buildPath(\n");
    source.push_str("  pathTemplate: string,\n");
    source.push_str("  pathParams: readonly EndpointPathParam[],\n");
    source.push_str("  request: ClientRequestShape,\n");
    source.push_str("): string {\n");
    source.push_str("  const requestRecord = request as Record<string, unknown>;\n");
    source.push_str("  let path = pathTemplate;\n\n");
    source.push_str("  for (const pathParam of pathParams) {\n");
    source.push_str("    const value = requestRecord[pathParam.wireName];\n\n");
    source.push_str("    if (value === undefined || value === null) {\n");
    source.push_str("      throw new Error(`missing path parameter ${pathParam.wireName}`);\n");
    source.push_str("    }\n\n");
    source.push_str(
        "    path = path.replace(`{${pathParam.wireName}}`, encodeURIComponent(String(value)));\n",
    );
    source.push_str("  }\n\n");
    source.push_str("  return path;\n");
    source.push_str("}\n\n");
    source.push_str("function buildJsonBody(\n");
    source.push_str("  pathParams: readonly EndpointPathParam[],\n");
    source.push_str("  hasJsonBody: boolean,\n");
    source.push_str("  request: ClientRequestShape,\n");
    source.push_str("): Record<string, unknown> | undefined {\n");
    source.push_str("  if (!hasJsonBody) {\n");
    source.push_str("    return undefined;\n");
    source.push_str("  }\n\n");
    source.push_str("  const requestRecord = request as Record<string, unknown>;\n");
    source.push_str(
        "  const pathParamNames = new Set(pathParams.map((pathParam) => pathParam.wireName));\n\n",
    );
    source.push_str("  return Object.fromEntries(\n");
    source.push_str("    Object.entries(requestRecord).filter(([fieldName]) => !pathParamNames.has(fieldName)),\n");
    source.push_str("  );\n");
    source.push_str("}\n\n");
    source.push_str("function buildHeaders(\n");
    source.push_str("  hasJsonBody: boolean,\n");
    source.push_str("  acceptsEventStream: boolean,\n");
    source.push_str("): Record<string, string> {\n");
    source.push_str("  const headers: Record<string, string> = {};\n\n");
    source.push_str("  if (hasJsonBody) {\n");
    source.push_str("    headers[\"content-type\"] = \"application/json\";\n");
    source.push_str("  }\n\n");
    source.push_str("  if (acceptsEventStream) {\n");
    source.push_str("    headers[\"accept\"] = \"text/event-stream\";\n");
    source.push_str("  }\n\n");
    source.push_str("  return headers;\n");
    source.push_str("}\n");

    source
}

/// Renders the browser `fetch` transport and shared HTTP error decoding helpers.
fn render_fetch_module() -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);

    source.push_str(
        "import { ContractTransportError, type ContractCallOptions, type ContractErrorPayload, type ContractTransport, type ContractTransportRequest } from \"./transport.js\";\n\n",
    );
    source.push_str("export type FetchTransportOptions = {\n");
    source.push_str("  baseUrl?: string;\n");
    source.push_str("  fetch?: typeof globalThis.fetch;\n");
    source.push_str("};\n\n");
    source.push_str("export function createFetchTransport(\n");
    source.push_str("  options: FetchTransportOptions = {},\n");
    source.push_str("): ContractTransport {\n");
    source.push_str("  const fetchImplementation = options.fetch ?? globalThis.fetch;\n\n");
    source.push_str("  if (fetchImplementation === undefined) {\n");
    source.push_str("    throw new Error(\"global fetch is not available\");\n");
    source.push_str("  }\n\n");
    source.push_str("  const baseUrl = options.baseUrl ?? \"\";\n\n");
    source.push_str("  async function execute(\n");
    source.push_str("    request: ContractTransportRequest,\n");
    source.push_str("    callOptions: ContractCallOptions | undefined,\n");
    source.push_str("  ): Promise<Response> {\n");
    source.push_str("    return fetchImplementation(resolveUrl(baseUrl, request.path), {\n");
    source.push_str("      method: request.method,\n");
    source.push_str("      headers: request.headers,\n");
    source.push_str(
        "      body: request.body === undefined ? undefined : JSON.stringify(request.body),\n",
    );
    source.push_str("      signal: callOptions?.signal,\n");
    source.push_str("    });\n");
    source.push_str("  }\n\n");
    source.push_str("  return {\n");
    source.push_str(
        "    async send<TResponse>(request: ContractTransportRequest, callOptions?: ContractCallOptions): Promise<TResponse> {\n",
    );
    source.push_str("      const response = await execute(request, callOptions);\n");
    source.push_str("      const responseBody = await readResponseBody(response);\n\n");
    source.push_str("      if (!response.ok) {\n");
    source.push_str("        throw toTransportError(response.status, responseBody);\n");
    source.push_str("      }\n\n");
    source.push_str("      return responseBody as TResponse;\n");
    source.push_str("    },\n\n");
    source.push_str(
        "    async *stream<TEvent>(request: ContractTransportRequest, callOptions?: ContractCallOptions): AsyncGenerator<TEvent> {\n",
    );
    source.push_str("      const response = await execute(request, callOptions);\n\n");
    source.push_str("      if (!response.ok) {\n");
    source.push_str(
        "        throw toTransportError(response.status, await readResponseBody(response));\n",
    );
    source.push_str("      }\n\n");
    source.push_str("      if (response.body === null) {\n");
    source.push_str("        throw new ContractTransportError({\n");
    source.push_str("          code: \"stream_unavailable\",\n");
    source.push_str(
        "          message: `operation ${request.operationName} returned no response stream`,\n",
    );
    source.push_str("          status: response.status,\n");
    source.push_str("          responseBody: null,\n");
    source.push_str("        });\n");
    source.push_str("      }\n\n");
    source.push_str("      yield* readEventStream<TEvent>(response.body, request);\n");
    source.push_str("    },\n");
    source.push_str("  };\n");
    source.push_str("}\n\n");
    source.push_str("export function resolveUrl(baseUrl: string, path: string): string {\n");
    source.push_str("  if (baseUrl === \"\") {\n");
    source.push_str("    return path;\n");
    source.push_str("  }\n\n");
    source.push_str("  return new URL(path, baseUrl).toString();\n");
    source.push_str("}\n\n");
    source.push_str(
        "export function decodeErrorEnvelope(body: unknown): ContractErrorPayload | null {\n",
    );
    source.push_str("  if (!isRecord(body)) {\n");
    source.push_str("    return null;\n");
    source.push_str("  }\n\n");
    source.push_str("  const error = body.error;\n\n");
    source.push_str("  if (!isRecord(error) || typeof error.code !== \"string\" || typeof error.message !== \"string\") {\n");
    source.push_str("    return null;\n");
    source.push_str("  }\n\n");
    source.push_str("  return {\n");
    source.push_str("    code: error.code,\n");
    source.push_str("    message: error.message,\n");
    source.push_str("  };\n");
    source.push_str("}\n\n");
    source.push_str(
        "/** Yields one decoded event per server-sent frame until the response stream ends. */\n",
    );
    source.push_str("async function* readEventStream<TEvent>(\n");
    source.push_str("  body: ReadableStream<Uint8Array>,\n");
    source.push_str("  request: ContractTransportRequest,\n");
    source.push_str("): AsyncGenerator<TEvent> {\n");
    source.push_str("  const reader = body.getReader();\n");
    source.push_str("  const decoder = new TextDecoder();\n");
    source.push_str("  let buffer = \"\";\n\n");
    source.push_str("  try {\n");
    source.push_str("    for (;;) {\n");
    source.push_str("      const { done, value } = await reader.read();\n\n");
    source.push_str("      if (done) {\n");
    source.push_str("        return;\n");
    source.push_str("      }\n\n");
    source.push_str("      buffer += decoder.decode(value, { stream: true });\n\n");
    source.push_str("      for (;;) {\n");
    source.push_str("        const frame = takeEventFrame(buffer);\n\n");
    source.push_str("        if (frame === null) {\n");
    source.push_str("          break;\n");
    source.push_str("        }\n\n");
    source.push_str("        buffer = frame.rest;\n");
    source.push_str("        const event = decodeEventFrame<TEvent>(frame.frame, request);\n\n");
    source.push_str("        if (event !== null) {\n");
    source.push_str("          yield event;\n");
    source.push_str("        }\n");
    source.push_str("      }\n");
    source.push_str("    }\n");
    source.push_str("  } finally {\n");
    source.push_str("    await reader.cancel();\n");
    source.push_str("  }\n");
    source.push_str("}\n\n");
    source.push_str("/** Splits off the first complete frame, leaving any partial trailing frame buffered. */\n");
    source.push_str(
        "function takeEventFrame(buffer: string): { frame: string; rest: string } | null {\n",
    );
    source.push_str("  const separator = /\\r?\\n\\r?\\n/.exec(buffer);\n\n");
    source.push_str("  if (separator === null) {\n");
    source.push_str("    return null;\n");
    source.push_str("  }\n\n");
    source.push_str("  return {\n");
    source.push_str("    frame: buffer.slice(0, separator.index),\n");
    source.push_str("    rest: buffer.slice(separator.index + separator[0].length),\n");
    source.push_str("  };\n");
    source.push_str("}\n\n");
    source.push_str("/** Decodes one frame's `data` lines, returning null for comment-only keep-alive frames. */\n");
    source.push_str("function decodeEventFrame<TEvent>(\n");
    source.push_str("  frame: string,\n");
    source.push_str("  request: ContractTransportRequest,\n");
    source.push_str("): TEvent | null {\n");
    source.push_str("  const dataLines: string[] = [];\n\n");
    source.push_str("  for (const line of frame.split(/\\r?\\n/)) {\n");
    source.push_str("    if (line.startsWith(\":\")) {\n");
    source.push_str("      continue;\n");
    source.push_str("    }\n\n");
    source.push_str("    const separatorIndex = line.indexOf(\":\");\n\n");
    source.push_str(
        "    if (separatorIndex === -1 || line.slice(0, separatorIndex) !== \"data\") {\n",
    );
    source.push_str("      continue;\n");
    source.push_str("    }\n\n");
    source.push_str("    const value = line.slice(separatorIndex + 1);\n");
    source.push_str("    dataLines.push(value.startsWith(\" \") ? value.slice(1) : value);\n");
    source.push_str("  }\n\n");
    source.push_str("  if (dataLines.length === 0) {\n");
    source.push_str("    return null;\n");
    source.push_str("  }\n\n");
    source.push_str("  const payload = dataLines.join(\"\\n\");\n\n");
    source.push_str("  let decoded: unknown;\n\n");
    source.push_str("  try {\n");
    source.push_str("    decoded = JSON.parse(payload) as unknown;\n");
    source.push_str("  } catch {\n");
    source.push_str("    throw new ContractTransportError({\n");
    source.push_str("      code: \"stream_decode_error\",\n");
    source.push_str(
        "      message: `operation ${request.operationName} sent an event that is not valid JSON`,\n",
    );
    source.push_str("      status: null,\n");
    source.push_str("      responseBody: payload,\n");
    source.push_str("    });\n");
    source.push_str("  }\n\n");
    source.push_str("  const errorPayload = decodeErrorEnvelope(decoded);\n\n");
    source.push_str("  if (errorPayload !== null) {\n");
    source.push_str("    throw new ContractTransportError({\n");
    source.push_str("      code: errorPayload.code,\n");
    source.push_str("      message: errorPayload.message,\n");
    source.push_str("      status: null,\n");
    source.push_str("      responseBody: decoded,\n");
    source.push_str("    });\n");
    source.push_str("  }\n\n");
    source.push_str("  return decoded as TEvent;\n");
    source.push_str("}\n\n");
    source.push_str("async function readResponseBody(response: Response): Promise<unknown> {\n");
    source.push_str("  const bodyText = await response.text();\n\n");
    source.push_str("  if (bodyText === \"\") {\n");
    source.push_str("    return null;\n");
    source.push_str("  }\n\n");
    source.push_str("  try {\n");
    source.push_str("    return JSON.parse(bodyText) as unknown;\n");
    source.push_str("  } catch {\n");
    source.push_str("    return bodyText;\n");
    source.push_str("  }\n");
    source.push_str("}\n\n");
    source.push_str("function toTransportError(status: number, responseBody: unknown): ContractTransportError {\n");
    source.push_str("  const decodedError = decodeErrorEnvelope(responseBody);\n\n");
    source.push_str("  if (decodedError !== null) {\n");
    source.push_str("    return new ContractTransportError({\n");
    source.push_str("      code: decodedError.code,\n");
    source.push_str("      message: decodedError.message,\n");
    source.push_str("      status,\n");
    source.push_str("      responseBody,\n");
    source.push_str("    });\n");
    source.push_str("  }\n\n");
    source.push_str("  return new ContractTransportError({\n");
    source.push_str("    code: \"http_error\",\n");
    source.push_str("    message: `HTTP request failed with status ${status}`,\n");
    source.push_str("    status,\n");
    source.push_str("    responseBody,\n");
    source.push_str("  });\n");
    source.push_str("}\n\n");
    source.push_str("function isRecord(value: unknown): value is Record<string, unknown> {\n");
    source.push_str("  return typeof value === \"object\" && value !== null;\n");
    source.push_str("}\n");

    source
}

/// Renders the root package entrypoint for DTOs and generated client helpers.
fn render_index_module() -> String {
    let mut source = String::from(GENERATED_FILE_HEADER);

    source.push_str("export * from \"./client.js\";\n");
    source.push_str("export * from \"./endpoints.js\";\n");
    source.push_str("export * from \"./transport.js\";\n");
    source.push_str("export * from \"./agent.js\";\n");
    source.push_str("export * from \"./project.js\";\n");
    source.push_str("export * from \"./project-work-context.js\";\n");
    source.push_str("export * from \"./session.js\";\n");
    source.push_str("export * from \"./skill.js\";\n");
    source.push_str("export * from \"./task.js\";\n");

    source
}

/// Places one unary or streaming operation on the generated client.
#[derive(Clone, Copy)]
enum ClientMember<'a> {
    Unary(&'a FrontendEndpoint),
    Stream(&'a FrontendStreamEndpoint),
}

impl ClientMember<'_> {
    /// Returns the member name this operation takes on its client namespace.
    fn member_name(&self) -> &'static str {
        match self {
            ClientMember::Unary(endpoint) => endpoint.member_name,
            ClientMember::Stream(stream_endpoint) => stream_endpoint.member_name,
        }
    }

    /// Returns the flat wire-level operation name this member dispatches to.
    fn operation_name(&self) -> &'static str {
        match self {
            ClientMember::Unary(endpoint) => endpoint.operation_name,
            ClientMember::Stream(stream_endpoint) => stream_endpoint.operation_name,
        }
    }

    /// Returns the client namespace that owns this member.
    fn namespace(&self) -> &'static str {
        match self {
            ClientMember::Unary(endpoint) => endpoint.namespace,
            ClientMember::Stream(stream_endpoint) => stream_endpoint.namespace,
        }
    }
}

/// Groups unary and streaming operations into their client namespaces.
///
/// Unary operations keep the manifest declaration order and streams follow them
/// inside the namespace they share, so adding a stream never reorders the
/// generated client surface.
fn group_client_members<'a>(
    endpoints: &'a [FrontendEndpoint],
    stream_endpoints: &'a [FrontendStreamEndpoint],
) -> Vec<(&'static str, Vec<ClientMember<'a>>)> {
    let members = endpoints
        .iter()
        .map(ClientMember::Unary)
        .chain(stream_endpoints.iter().map(ClientMember::Stream));
    let mut grouped: Vec<(&'static str, Vec<ClientMember<'a>>)> = Vec::new();

    for member in members {
        match grouped
            .iter_mut()
            .find(|(namespace, _)| *namespace == member.namespace())
        {
            Some((_, namespace_members)) => namespace_members.push(member),
            None => grouped.push((member.namespace(), vec![member])),
        }
    }

    grouped
}

/// Collects the TypeScript DTO imports needed by the generated endpoint manifest.
fn collect_contract_type_imports(
    endpoints: &[FrontendEndpoint],
    stream_endpoints: &[FrontendStreamEndpoint],
) -> BTreeMap<&'static str, BTreeSet<&'static str>> {
    let mut imports: BTreeMap<&'static str, BTreeSet<&'static str>> = BTreeMap::new();

    for type_name in
        endpoints
            .iter()
            .flat_map(|endpoint| [endpoint.request_type, endpoint.response_type])
            .chain(stream_endpoints.iter().flat_map(|stream_endpoint| {
                [stream_endpoint.request_type, stream_endpoint.event_type]
            }))
    {
        imports
            .entry(contract_module_for_type(type_name))
            .or_default()
            .insert(type_name);
    }

    imports
}

/// Maps one exported contract type name to the TypeScript module that contains it.
fn contract_module_for_type(type_name: &str) -> &'static str {
    match type_name {
        "CreateProjectRequest"
        | "CreateProjectResponse"
        | "DeleteProjectRequest"
        | "DeleteProjectResponse"
        | "GetProjectRequest"
        | "GetProjectResponse"
        | "ListProjectsRequest"
        | "ListProjectsResponse"
        | "UpdateProjectRequest"
        | "UpdateProjectResponse" => "project",
        "OpenProjectWorkContextRequest"
        | "OpenProjectWorkContextResponse"
        | "ProjectWorkContext"
        | "RenewProjectWorkContextRequest"
        | "RenewProjectWorkContextResponse" => "project-work-context",
        "CreateTaskRequest" | "CreateTaskResponse" | "DeleteTaskRequest" | "DeleteTaskResponse"
        | "GetTaskRequest" | "GetTaskResponse" | "ListTasksRequest" | "ListTasksResponse"
        | "UpdateTaskRequest" | "UpdateTaskResponse" => "task",
        "CreateSessionRequest"
        | "CreateSessionResponse"
        | "DeleteSessionRequest"
        | "DeleteSessionResponse"
        | "GetSessionRequest"
        | "GetSessionResponse"
        | "ListSessionsRequest"
        | "ListSessionsResponse"
        | "SessionEvent"
        | "SubscribeSessionEventsRequest"
        | "UpdateSessionRequest"
        | "UpdateSessionResponse" => "session",
        "CreateSkillRequest"
        | "CreateSkillResponse"
        | "DeleteSkillRequest"
        | "DeleteSkillResponse"
        | "GetSkillRequest"
        | "GetSkillResponse"
        | "ListSkillsRequest"
        | "ListSkillsResponse"
        | "UpdateSkillRequest"
        | "UpdateSkillResponse" => "skill",
        "CreateAgentRequest"
        | "CreateAgentResponse"
        | "DeleteAgentRequest"
        | "DeleteAgentResponse"
        | "GetAgentRequest"
        | "GetAgentResponse"
        | "ListAgentsRequest"
        | "ListAgentsResponse"
        | "UpdateAgentRequest"
        | "UpdateAgentResponse" => "agent",
        other => panic!("unknown contract type `{other}`"),
    }
}

/// Renders one HTTP method enum value as the wire-level string used by the generated SDK.
fn render_http_method(endpoint: &FrontendEndpoint) -> &'static str {
    match endpoint.method {
        ora_contracts::FrontendHttpMethod::Get => "GET",
        ora_contracts::FrontendHttpMethod::Post => "POST",
        ora_contracts::FrontendHttpMethod::Put => "PUT",
        ora_contracts::FrontendHttpMethod::Delete => "DELETE",
    }
}

/// Renders one streaming endpoint's HTTP method as the wire-level string used by the generated SDK.
fn render_stream_http_method(stream_endpoint: &FrontendStreamEndpoint) -> &'static str {
    match stream_endpoint.method {
        ora_contracts::FrontendHttpMethod::Get => "GET",
        ora_contracts::FrontendHttpMethod::Post => "POST",
        ora_contracts::FrontendHttpMethod::Put => "PUT",
        ora_contracts::FrontendHttpMethod::Delete => "DELETE",
    }
}

/// Renders the endpoint path parameter metadata into a TypeScript array literal.
fn render_path_params(path_params: &[FrontendPathParam]) -> String {
    if path_params.is_empty() {
        return "[]".to_string();
    }

    let mut rendered = String::from("[");

    for (index, path_param) in path_params.iter().enumerate() {
        if index > 0 {
            rendered.push_str(", ");
        }

        rendered.push_str("{ ");
        rendered.push_str("rustFieldName: \"");
        rendered.push_str(path_param.rust_field_name);
        rendered.push_str("\", ");
        rendered.push_str("wireName: \"");
        rendered.push_str(path_param.wire_name);
        rendered.push_str("\" }");
    }

    rendered.push(']');
    rendered
}

/// Renders a sorted import set into a comma-separated type list.
fn join_types(types: &BTreeSet<&'static str>) -> String {
    types.iter().copied().collect::<Vec<_>>().join(", ")
}

#[cfg(test)]
mod tests {
    use super::{
        render_client_module, render_endpoints_module, render_fetch_module, render_index_module,
        run_export_contracts,
    };
    use ora_contracts::{frontend_endpoints, frontend_stream_endpoints};
    use pretty_assertions::assert_eq;
    use std::fs;
    use tempfile::TempDir;

    /// Verifies the generated endpoint manifest preserves update-route path metadata.
    #[test]
    fn renders_endpoint_manifest_with_update_path_params() {
        let module = render_endpoints_module(frontend_endpoints(), frontend_stream_endpoints());

        assert!(module.contains("updateTask"));
        assert!(module.contains("pathTemplate: \"/api/tasks/{taskId}\""));
        assert!(module.contains("wireName: \"taskId\""));
    }

    /// Verifies the generated client strips path params from JSON request bodies.
    #[test]
    fn renders_client_with_path_body_split_helper() {
        let module = render_client_module(frontend_endpoints(), frontend_stream_endpoints());

        assert!(module.contains("Object.entries(requestRecord).filter"));
        assert!(module.contains("missing path parameter"));
    }

    /// Verifies the generated client groups operations into namespaces over the flat wire names.
    #[test]
    fn renders_client_with_namespaced_operations() {
        let module = render_client_module(frontend_endpoints(), frontend_stream_endpoints());

        assert!(module.contains("  project: {\n"));
        assert!(module.contains("    create: ClientOperation<\"createProject\">;\n"));
        assert!(module.contains(
            "      update: (request, options) => executeOperation(\"updateTask\", request, transport, options),\n"
        ));
        assert!(module.contains("  projectWorkContext: {\n"));
    }

    /// Verifies streaming operations land on the namespace they share with unary operations.
    #[test]
    fn renders_client_with_streaming_operations() {
        let module = render_client_module(frontend_endpoints(), frontend_stream_endpoints());

        assert!(
            module.contains("    subscribe: ClientStreamOperation<\"subscribeSessionEvents\">;\n")
        );
        assert!(module.contains(
            "      subscribe: (request, options) => executeStreamOperation(\"subscribeSessionEvents\", request, transport, options),\n"
        ));
        assert!(module.contains("    delete: ClientOperation<\"deleteSession\">;\n"));
    }

    /// Verifies the streaming manifest exports the event type separately from unary responses.
    #[test]
    fn renders_stream_endpoint_manifest_with_event_types() {
        let module = render_endpoints_module(frontend_endpoints(), frontend_stream_endpoints());

        assert!(module.contains("export const streamEndpoints = {"));
        assert!(module.contains("  subscribeSessionEvents: SessionEvent;\n"));
        assert!(module.contains("    pathTemplate: \"/api/sessions/{sessionId}/events\",\n"));
    }

    /// Verifies the fetch transport decodes server-sent frames rather than buffering the body.
    #[test]
    fn renders_fetch_transport_with_event_stream_reader() {
        let module = render_fetch_module();

        assert!(module.contains("readEventStream"));
        assert!(module.contains("text/event-stream") || module.contains("takeEventFrame"));
        assert!(module.contains("stream_decode_error"));
    }

    /// Verifies the fetch transport module includes the shared error-decoding helpers.
    #[test]
    fn renders_fetch_transport_with_error_decoding() {
        let module = render_fetch_module();

        assert!(module.contains("decodeErrorEnvelope"));
        assert!(module.contains("ContractTransportError"));
        assert!(module.contains("resolveUrl"));
    }

    /// Verifies the full export workflow writes DTOs and generated SDK runtime files together.
    #[test]
    fn writes_contract_package_files() {
        let workspace_root = TempDir::new().unwrap_or_else(|error| {
            panic!("failed to create workspace root: {error}");
        });
        let package_source_directory = workspace_root.path().join("packages/contracts/src");
        fs::create_dir_all(&package_source_directory).unwrap_or_else(|error| {
            panic!("failed to create package source directory: {error}");
        });

        run_export_contracts(workspace_root.path()).unwrap_or_else(|error| {
            panic!("expected export workflow to succeed: {error}");
        });

        let generated_files = [
            "agent.ts",
            "client.ts",
            "endpoints.ts",
            "fetch.ts",
            "index.ts",
            "project.ts",
            "session.ts",
            "skill.ts",
            "task.ts",
            "transport.ts",
        ];

        for generated_file in generated_files {
            let output_path = package_source_directory.join(generated_file);
            assert!(
                output_path.exists(),
                "missing generated file {:?}",
                output_path
            );
        }

        let index_module = fs::read_to_string(package_source_directory.join("index.ts"))
            .unwrap_or_else(|error| panic!("failed to read generated index module: {error}"));

        assert!(index_module.contains("export * from \"./agent.js\";"));
        assert!(index_module.contains("export * from \"./skill.js\";"));
        assert_eq!(index_module, render_index_module(),);
    }
}
